server:
  port: 8080
  base-url: http://dev.faraone.ovh:81
scheduledFor: execution
grpc:
  server:
    port: 3030
spring:
  application:
    name: bank
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev.faraone.ovh:3307/bank
    username: developer
    password: password4testing
exchange-currency:
  endpoint: https://v6.exchangerate-api.com/v6/
  api-key: ceb94d443f6398dd5e640cd1
  base-currency: USD
bank-info:
  bank-bin: "593796"
  bank-code: "59379"
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 30
active-mq:
  bank-users: bank-accounts
  broker-url: tcp://activemq:61616
  emails: emails
  bank-deposit: bank-deposit
  bank-withdrawal: bank-withdrawal
  bank-account-deletion: bank-account-deletion