server:
  port: 8080
scheduledFor: execution
spring:
  jpa:
    open-in-view: false
    show-sql: false
  profiles:
    active: "external"
exchange-currency:
  endpoint: https://v6.exchangerate-api.com/v6/
  api-key: ceb94d443f6398dd5e640cd1
  base-currency: USD
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 30

---
#External DB
active-mq:
  bank-users: bank-accounts
  broker-url: tcp://dev.faraone.ovh:61616
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev.faraone.ovh:3307/bank
    username: developer
    password: password4testing
  config:
    activate:
      on-profile: external

---
##local mySQL config
active-mq:
  bank-users: bank-accounts
  broker-url: tcp://localhost:61616
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/bank?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    show-sql: true
    database: mysql
    generate-ddl: true
  config:
    activate:
      on-profile: mysql